name: Kill Checklists

on:
  schedule:
    # every day at 8PM/9PM, 10 minutes staggered
    - cron: "5 0 * * 1"  
    - cron: "15 0 * * 2"
    - cron: "25 0 * * 3"
    - cron: "35 0 * * 4"
    - cron: "25 0 * * 5"
    - cron: "15 0 * * 6"  
    - cron: "5 0 * * 0"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    environment: checklistKiller

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Bot
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          STORE_NUMBER: ${{ secrets.STORE_NUMBER }}
          DEBUG: pw:api
        run: node bot.js
